spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codebuffer    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:    generate-ddl: true
    show-sql: true    hibernate:      ddl-auto: update  application:    name: DEPARTMENT-SERVICE
server:  port: 9001
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/      
  instance:
    hostname: localhost